title: Strava Coach
description: Public assets for an open-source Strava Custom GPT project
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  quiet_deps: true
exclude:
  - actions/README.md
  - assets/README.md
  - data/README.md
