{
  "selected_paths": [
    "/athlete",
    "/athlete/zones",
    "/athletes/{id}/stats",
    "/athlete/activities",
    "/activities/{id}",
    "/activities/{id}/streams",
    "/activities/{id}/zones"
  ],
  "source_urls": [
    "https://developers.strava.com/swagger/swagger.json",
    "https://developers.strava.com/swagger/athlete.json",
    "https://developers.strava.com/swagger/activity.json",
    "https://developers.strava.com/swagger/activity_stats.json",
    "https://developers.strava.com/swagger/stream.json",
    "https://developers.strava.com/swagger/zones.json",
    "https://developers.strava.com/swagger/fault.json"
  ],
  "official_spec": {
    "openapi": "3.0.3",
    "info": {
      "title": "Strava API v3",
      "description": "The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to deve[...]",
      "version": "3.0.0"
    },
    "servers": [
      {
        "url": "https://www.strava.com/api/v3"
      }
    ],
    "security": [
      {
        "strava_oauth": []
      }
    ],
    "paths": {
      "/athlete": {
        "get": {
          "operationId": "getLoggedInAthlete",
          "summary": "Get Authenticated Athlete",
          "description": "Returns the currently authenticated athlete. Tokens with profile:read_all scope will receive a detailed athlete representation; all others will receive a summary representation.",
          "tags": [
            "Athletes"
          ],
          "security": [
            {
              "strava_oauth": [
                "profile:read_all"
              ]
            }
          ]
        }
      },
      "/athlete/zones": {
        "get": {
          "operationId": "getLoggedInAthleteZones",
          "summary": "Get Zones",
          "description": "Returns the the authenticated athlete's heart rate and power zones. Requires profile:read_all.",
          "tags": [
            "Athletes"
          ],
          "security": [
            {
              "strava_oauth": [
                "profile:read_all"
              ]
            }
          ]
        }
      },
      "/athletes/{id}/stats": {
        "get": {
          "operationId": "getStats",
          "summary": "Get Athlete Stats",
          "description": "Returns the activity stats of an athlete. Only includes data from activities set to Everyone visibilty.",
          "tags": [
            "Athletes"
          ]
        }
      },
      "/athlete/activities": {
        "get": {
          "operationId": "getLoggedInAthleteActivities",
          "summary": "List Athlete Activities",
          "description": "Returns the activities of an athlete for a specific identifier. Requires activity:read. Only Me activities will be filtered out unless requested by a token with activity:read_all.",
          "tags": [
            "Activities"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      },
      "/activities/{id}": {
        "get": {
          "operationId": "getActivityById",
          "summary": "Get Activity",
          "description": "Returns the given activity that is owned by the authenticated athlete. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.\n\nWe strongly encourage you to display the appropriate attribution that identifies Garmin as the data source and the device name in your application. Please see example below from VeloViewer (that provides an attribution for a Garmin Forerunner device).\n\n![Attribution](/images/device-at[...]",
          "tags": [
            "Activities"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      },
      "/activities/{id}/streams": {
        "get": {
          "operationId": "getActivityStreams",
          "summary": "Get Activity Streams",
          "description": "Returns the given activity's streams. Requires activity:read scope. Requires activity:read_all scope for Only Me activities.",
          "tags": [
            "Streams"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      },
      "/activities/{id}/zones": {
        "get": {
          "operationId": "getZonesByActivityId",
          "summary": "Get Activity Zones",
          "description": "Summit Feature. Returns the zones of a given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
          "tags": [
            "Activities"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      }
    },
    "components": {
      "securitySchemes": {
        "strava_oauth": {
          "type": "oauth2",
          "flows": {
            "authorizationCode": {
              "authorizationUrl": "https://www.strava.com/api/v3/oauth/authorize",
              "tokenUrl": "https://www.strava.com/api/v3/oauth/token",
              "scopes": {
                "read": "Read public segments, public routes, public profile data, public posts, public events, club feeds, and leaderboards",
                "read_all": "Read private routes, private segments, and private events for the user",
                "profile:read_all": "Read all profile information even if the user has set their profile visibility to Followers or Only You",
                "profile:write": "Update the user's weight and Functional Threshold Power (FTP), and access to star or unstar segments on their behalf",
                "activity:read": "Read the user's activity data for activities that are visible to Everyone and Followers, excluding privacy zone data",
                "activity:read_all": "The same access as activity:read, plus privacy zone data and access to read the user's activities with visibility set to Only You",
                "activity:write": "Access to create manual activities and uploads, and access to edit any activities that are visible to the app, based on activity read access level"
              }
            }
          }
        }
      }
    }
  },
  "spec": {
    "openapi": "3.1.0",
    "info": {
      "title": "Strava API v3",
      "description": "The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to deve[...]",
      "version": "3.0.0+strava-coach.1"
    },
    "servers": [
      {
        "url": "https://www.strava.com/api/v3"
      }
    ],
    "security": [
      {
        "strava_oauth": []
      }
    ],
    "paths": {
      "/athlete": {
        "get": {
          "operationId": "getLoggedInAthlete",
          "summary": "Get Authenticated Athlete",
          "description": "Returns the currently authenticated athlete. Tokens with profile:read_all scope will receive a detailed athlete representation; all others will receive a summary representation.",
          "tags": [
            "Athletes"
          ],
          "security": [
            {
              "strava_oauth": [
                "profile:read_all"
              ]
            }
          ]
        }
      },
      "/athlete/zones": {
        "get": {
          "operationId": "getLoggedInAthleteZones",
          "summary": "Get Zones",
          "description": "Returns the the authenticated athlete's heart rate and power zones. Requires profile:read_all.",
          "tags": [
            "Athletes"
          ],
          "security": [
            {
              "strava_oauth": [
                "profile:read_all"
              ]
            }
          ]
        }
      },
      "/athletes/{id}/stats": {
        "get": {
          "operationId": "getStats",
          "summary": "Get Athlete Stats",
          "description": "Returns the activity stats of an athlete. Only includes data from activities set to Everyone visibilty.",
          "tags": [
            "Athletes"
          ]
        }
      },
      "/athlete/activities": {
        "get": {
          "operationId": "getLoggedInAthleteActivities",
          "summary": "List Athlete Activities",
          "description": "Returns the activities of an athlete for a specific identifier. Requires activity:read. Only Me activities will be filtered out unless requested by a token with activity:read_all.",
          "tags": [
            "Activities"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      },
      "/activities/{id}": {
        "get": {
          "operationId": "getActivityById",
          "summary": "Get Activity",
          "description": "Returns the given activity that is owned by the authenticated athlete. Requires activity:read for Everyone and Followers activities and activity:read_all for Only Me activities.",
          "tags": [
            "Activities"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      },
      "/activities/{id}/streams": {
        "get": {
          "operationId": "getActivityStreams",
          "summary": "Get Activity Streams",
          "description": "Returns the given activity's streams. Requires activity:read scope. Requires activity:read_all scope for Only Me activities.",
          "tags": [
            "Streams"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      },
      "/activities/{id}/zones": {
        "get": {
          "operationId": "getZonesByActivityId",
          "summary": "Get Activity Zones",
          "description": "Summit Feature. Returns the zones of a given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
          "tags": [
            "Activities"
          ],
          "security": [
            {
              "strava_oauth": [
                "activity:read"
              ]
            },
            {
              "strava_oauth": [
                "activity:read_all"
              ]
            }
          ]
        }
      }
    },
    "components": {
      "securitySchemes": {
        "strava_oauth": {
          "type": "oauth2",
          "flows": {
            "authorizationCode": {
              "authorizationUrl": "https://www.strava.com/api/v3/oauth/authorize",
              "tokenUrl": "https://www.strava.com/api/v3/oauth/token",
              "scopes": {
                "read": "Read public segments, public routes, public profile data, public posts, public events, club feeds, and leaderboards",
                "read_all": "Read private routes, private segments, and private events for the user",
                "profile:read_all": "Read all profile information even if the user has set their profile visibility to Followers or Only You",
                "profile:write": "Update the user's weight and Functional Threshold Power (FTP), and access to star or unstar segments on their behalf",
                "activity:read": "Read the user's activity data for activities that are visible to Everyone and Followers, excluding privacy zone data",
                "activity:read_all": "The same access as activity:read, plus privacy zone data and access to read the user's activities with visibility set to Only You",
                "activity:write": "Access to create manual activities and uploads, and access to edit any activities that are visible to the app, based on activity read access level"
              }
            }
          }
        }
      }
    }
  }
}
